name: Youtube

on:
  push:
    branches: ["main"]
    paths:
      - "bot/**"
      - ".github/workflows/youtube.yml"
  workflow_dispatch:

concurrency:
  group: "Youtube"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: node bot/youtube.js
